### ISSUE TITLE
Davinci Resolve 18: URL not being generated

### ISSUE THREAD

**Issue by AppsPackG** [autopkg/timsutton-recipes#107] opened 2023-07-10 11:36 UTC
I was getting the bad request issues until I downloaded the latest recipe from the #103 commit.

However I am now seeing this message after entering the registration info.

 'url': 'Error: Must register to be able to perform the download',

I am using lowercase country ID as anything else was generating the bad request.

**Comment by woodmember** [comment] 2023-07-25 04:27
Not seeing the reg issue. However I can confirm the precedes of the bad URL error as well. The issue occurs when getting Resolve Lite. Studio works fine, but every since 18.5 was released I get the following error when trying to download 18.5 lite:

curl: (3) URL using bad/illegal format or missing URL

**Comment by AppsPackG** [comment] 2023-07-27 07:31
I had previously tried adding those as I could see that they were mandatory fields if you navigate to the online registration form and it didn't help.  Having tried again this morning it does appear to be now working, so not sure what has changed.  Looking good though!

**Comment by peterkelm** [comment] 2023-09-06 10:49
I've filed a pull request for this: #111. All credit goes to @holo2015 for that fix, though - thank you so much!

**Comment by adrienlabigne** [comment] 2023-10-24 14:37
Hi, is it possible to merge your commit to master ?
I really need Davinci 18 in our labs, but cant do it manually.

Thanks in advance

**Comment by timsutton** [comment] 2023-10-27 00:33
https://github.com/autopkg/timsutton-recipes/pull/111 is merged, and I've also added the same change for the older versions. Thanks for yall's patience 👍

**Closed by timsutton** 2023-10-27 00:33 UTC
